name: pinta-casept # you probably want to 'snapcraft register <name>'
version: '1.6' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  pinta:
# TODO: Clean up this unix centipede of commands.
    command: desktop-launch $SNAP/bin/mono-wrapper $SNAP/usr/bin/mono-sgen --desktop $SNAP/lib/pinta/Pinta.exe
    plugs: [x11, opengl, home]        
parts:
  patch:
    plugin: dump
    source: mono-4.0.patch

  pinta:
    stage-packages:
      - libc6
      - libglib2.0-cil
      - libgtk2.0-cil
      - libmono-addins-gui0.2-cil
      - libmono-addins0.2-cil
      - libmono-cairo4.0-cil
      - libmono-corlib4.5-cil
      - libmono-posix4.0-cil
      - libmono-sharpzip4.84-cil
      - libmono-system-core4.0-cil 
      - libmono-system-xml4.0-cil
      - libmono-system4.0-cil
      - mono-runtime
    build-packages:
      - build-essential
      - pkg-config
      - patch
      - cli-common-dev
      - intltool
      - mono-devel
      - mono-xbuild 
      - libgtk2.0-cil-dev
      - libglade2.0-cil-dev
      - libmono-addins-cil-dev
      - libmono-addins-gui-cil-dev
    plugin: autotools
    source: https://github.com/PintaProject/Pinta/archive/1.6.tar.gz
    #Apply a patch so it builds with mono 4.x
    prepare: |
      patch -p 2 -i ../../patch/build/mono-4.0.patch 
    after: [patch, desktop-gtk2]

  mono-wrapper:
    plugin: copy
    files:
      mono-wrapper: bin/mono-wrapper
