#!/bin/sh
# This script sets the mono path so mono can find system DLLs within the snap.
# See https://stackoverflow.com/questions/14452550/how-can-i-configure-mono-to-use-the-correct-paths-to-etc-directory-when-the-pre
PKG_DIR=$SNAP/usr
export MONO_PATH=$PKG_DIR/lib/mono/4.0:$PKG_DIR/lib/mono/3.5:$PKG_DIR/lib/mono/2.0:$PKG_DIR/lib/mono/compat-2.0
export MONO_CONFIG=$SNAP/etc/mono/config
export MONO_CFG_DIR=$PKG_DIR/etc
#export C_INCLUDE_PATH=${PKG_DIR}/include
export MONO_REGISTRY_PATH=~/.mono/registry
export MONO_GAC_PREFIX=$PKG_DIR/lib/mono/gac/

exec "$@"
